### ISSUE TITLE
Mailverteiler anpassen

### ISSUE THREAD

**Issue by froko** [froko/pgl-homepage#13]
- Thomas Bitzi
- Ceo Benedetti
- Marcel Albisser

**Comment by froko** [comment]
Mailadresse von Thomas angepasst, Ceo ergänzt
Mailadresse von Marcel, auch angepasst, sieht zwar gleich aus...

**Comment by Bjiarni** [comment]
Nachtrag:
Prüfung der letzten Mails mit Ceo und Mäsi. --> ok
Mailverteiler scheint somit jetzt korrekt.
