### ISSUE TITLE
Audio Archiv Jubilatus

### ISSUE THREAD

**Issue by Bjiarni** [froko/pgl-homepage#20]
Ergänzung des Audio Archivs mit dem Tonträger Jubilatus > Download

**Comment by froko** [comment]
Bitte MP3 Versionen auf Contentful stellen.

**Comment by Bjiarni** [comment]
sind raufgeladen :)

**Comment by froko** [comment]
Seite wird demnächst aktualisiert.
Input von Gaudi (er sitzt grad vis-a-vis von mir im Zug): Wieso laden wir unsere CDs nicht auf Spotify und verdienen noch ein paar Rappen dabei? 
Bin selber auch kein Experte, aber ihr könnt das ja mal im Vorstand diskutieren.
